# Default values for Freqtrade.

image:
  repository: freqtradeorg/freqtrade
  pullPolicy: IfNotPresent
  tag: latest

strategy:
  type: Recreate

services:
  main:
    enabled: true
    port:
      port: 9876

env: {}
  # TZ: UTC
  # PUID: 1001
  # PGID: 1001


persistence:
  config:
    enabled: true
    mountPath: "/config"
    emptyDir: true
    accessMode: ReadWriteOnce
    size: 1Gi
    storageClass: ""


## TrueCharts Values

ingress:
  main:
    enabled: true
    # Used when including ingress using {{ include "common.ingress" . }}
    type: "HTTP"
    entrypoint: "websecure"
    certType: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        path: /
