apiVersion: v1
kind: ConfigMap
metadata:
  name: freqtrade-config
data:
  config.json: |
    {
      "strategy": "{{ .Values.appConf.strategy_name | quote }}"
    {{ toJson .Values.config | indent 4 }}
    }
